apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: local
  namespace: local-pipeline
spec:
  tasks:
  - name: execute-remote-pipeline
    taskRef:
      kind: Task
      name: execute-remote-pipeline
    params:
    - name: pipeline-name
      value: remote
    - name: pipeline-namespace
      value: remote-pipeline
    - name: openshift-server-url
      value: INSERT_OPENSHIFT_URL_HERE
    - name: openshift-token-secret
      value: pipeline-starter
